language: python
python:
  - "3.6"
cache: pip
install: "pip install -r requirements.txt"
before_script:
  - "export DISPLAY=:99.0"
  - "- "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16""
  - sleep 3
script: python -m unittest