language: python
sudo: required
cache: pip
python:
  - "3.6"
install:
  - sudo apt-get install python3-pyqt5
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install codecov
script: xvfb-run coverage run -m unittest
after_success:
  - coveralls
  - codecov
