language: python
sudo: false
python:
  - "3.6"
cache:
  - pip
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
install:
  - "pip install -r requirements.txt"
script: python -m unittest