language: python
python:
  - "3.6"
cache: pip
install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  - "sudo apt-get install -y libqt5-dev"
  - "- sudo apt-get install -y mesa-common-dev libgl1-mesa-dev libglu1-mesa-dev"
  - "pip install -r requirements.txt"
script: python -m unittest