language: python
sudo: false
python:
  - "3.6"
cache: pip

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sudo apt-get -qq update
  - sudo apt-get install -y matchbox-window-manager
install:
  - DISPLAY=:99 matchbox-window-manager &
  - sleep 5
  - "pip install -r requirements.txt"
script: python -m unittest
