language: python
cache: pip
python:
  - "3.6"
install:
  - pip uninstall -q -y pytest-xvfb
  - pip install -q pyqt5==5.9.2
  - pip install coveralls
  - pip install codecov
script: xvfb-run coverage run -m unittest
after_success:
  - coveralls
  - codecov
