language: python
sudo: required
python:
  - "3.6"
cache:
  - pip
before_script:
  - "sudo apt-get update"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
install:
  - "pip install PyQt5"
script: python -m unittest