language: python
sudo: required
python:
  - "3.6"
cache: pip
install: "pip install -r requirements.txt"
before_script:
  - export XVFBARGS="-screen 0 1280x1024x24"
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 5
script: python -m unittest
