language: python
sudo: required
python:
  - "3.6"
before_script:
  - "sudo apt-get update"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1400x900x24 -ac +extension GLX +render"
install:
  - "pip install PyQt5"
script: cd sofos && python -m unittest