language: python
sudo: required
python:
  - "3.6"
install:
  - "sudo apt-get install -qq libegl1-mesa"
  - "pip install -r requirements.txt"
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 5
script: python -m unittest -v
