language: python
sudo: false
python:
  - "3.6"
cache: pip

before_install:
  - "export DISPLAY=:99.0"
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x24"
  - sudo apt-get -qq update
  - sudo apt-get install -y matchbox-window-manager
install:
  - DISPLAY=:99 matchbox-window-manager &
  - sleep 5
  - "pip install -r requirements.txt"
script: python -m unittest
